In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [3]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# process the data
data = data.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [5]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])

In [6]:
# Onehot encode the "Geography" column
onehot_encoder_geography = OneHotEncoder(handle_unknown='ignore')
geography_encoded = onehot_encoder_geography.fit_transform(data[["Geography"]]).toarray()
geography_encoded_df = pd.DataFrame(geography_encoded, columns=onehot_encoder_geography.get_feature_names_out(["Geography"]))
geography_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# combine onehot encoded columns with the original dataframe
data = pd.concat([data.drop("Geography",axis=1),geography_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [18]:
# Split the data into features and target variable
X = data.drop("EstimatedSalary",axis=1)
Y = data["EstimatedSalary"]

In [19]:
# Split the data into training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [ ]:
# Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Save the encoders and scaler for future use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)
    
with open('onehot_encoder_geography.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geography, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [10]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Build the model
model = Sequential([
  Dense(64, activation='relu', input_shape=(X.shape[1],)),
  Dense(32, activation='relu'),
  Dense(1)
])

model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

WARNING:tensorflow:From d:\Python\ANN-Implementation\ANN-Regression\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From d:\Python\ANN-Implementation\ANN-Regression\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [14]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

# Setup tensorboard 
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Setup early stopping
early_stopping_callabck = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [20]:
# Train the model
history = model.fit(
  X_train, Y_train,
  validation_data=(X_test, Y_test),
  epochs=100,
  callbacks=[early_stopping_callabck, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From d:\Python\ANN-Implementation\ANN-Regression\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From d:\Python\ANN-Implementation\ANN-Regression\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 5ms/step - loss: 71318.5625 - mae: 71318.5625 - val_loss: 66795.8516 - val_mae: 66795.8516
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 65105.9219 - mae: 65105.9219 - val_loss: 60244.0664 - val_mae: 60244.0664
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 56572.9961 - mae: 56572.9961 - val_loss: 52159.5156 - val_mae: 52159.5156
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 52142.4023 - mae: 52142.4023 - val_loss: 50806.0273 - val_mae: 50806.0273
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 51628.7930 - mae: 51628.7930 - val_loss: 50615.5781 - val_mae: 50615.5781
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 51510.3711 - mae: 51510.3711 - val_loss: 51128.3477 - val_mae: 51128.3477
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 51324.0586 - mae: 51324.0586 - val_loss: 53620.2266 - val_mae: 53620.2266
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 51472.4297 - mae: 51472.4297 - val_loss: 50912.2148 - val_mae: 50912.2148
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 51252.0430 - mae: 51252.0430 - val_loss: 51299.8086 - val_mae: 51299.8086
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 51156.6172 - mae: 51156.6172 - val_loss: 50748.1133 - val_mae: 50748.1133
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 51077.1133 - mae: 51077.1133 - val_loss: 50631.1992 - val_mae: 50631.1992
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 51052.8047 - mae: 51052.8047 - val_loss: 50316.9258 - val_mae: 50316.9258
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 51114.8008 - mae: 51114.8008 - val_loss: 50498.6016 - val_mae: 50498.6016
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 51051.6875 - mae: 51051.6875 - val_loss: 50899.2305 - val_mae: 50899.2305
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 51125.4883 - mae: 51125.4883 - val_loss: 50703.5391 - val_mae: 50703.5391
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 50854.5664 - mae: 50854.5664 - val_loss: 50464.8633 - val_mae: 50464.8633
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50855.2305 - mae: 50855.2305 - val_loss: 50330.1680 - val_mae: 50330.1680
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50921.2734 - mae: 50921.2734 - val_loss: 51847.1953 - val_mae: 51847.1953
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50996.3242 - mae: 50996.3242 - val_loss: 50693.7930 - val_mae: 50693.7930
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 50975.0352 - mae: 50975.0352 - val_loss: 50429.7148 - val_mae: 50429.7148
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 50917.5000 - mae: 50917.5000 - val_loss: 50653.3086 - val_mae: 50653.3086
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 51153.1484 - mae: 51153.1484 - val_loss: 50320.0234 - val_mae: 50320.0234

In [27]:
# Add the env's Scripts folder to PATH so %tensorboard can find tensorboard.exe
import os, sys
scripts = os.path.join(os.path.dirname(sys.executable), "Scripts")
os.environ["PATH"] = scripts + os.pathsep + os.environ["PATH"]
os.environ["TENSORBOARD_BINARY"] = os.path.join(scripts, "tensorboard.exe")

# Load tensorboard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [30]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 13900), started 0:00:20 ago. (Use '!kill 13900' to kill it.)

In [31]:
# Evaluate the model on the test set
test_loss,test_mae = model.evaluate(X_test,Y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 [==============================] - 0s 2ms/step - loss: 50316.9258 - mae: 50316.9258
Test Loss: 50316.92578125, Test MAE: 50316.92578125

In [32]:
model.save('ann_regression_model.h5')

d:\Python\ANN-Implementation\ANN-Regression\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(